### ISSUE TITLE
Making bestiary.yaml manageable

### ISSUE THREAD

**Issue by Faaab** [dstrelau/nimble.monster#1]
Hey there! The website looks fantastic 😊 I’d love to contribute to the code when I can find the time.

I was writing up some technical thoughts on the Nimble Discord when I realized, “This would probably make more sense on GitHub!” 😅

You’ve done a great job with the bestiary’s data structure—it’s really accessible, even for non-coders, with minimal guidance. And it’s clear and straightforward to work with, which is awesome. I did want to suggest a small change for scalability: having all monsters in a single YAML file could become a bit tricky to manage as the project grows, especially if you want to programmatically add or modify monsters down the line.

Here’s a solution I was thinking about:

- Set up a `monsters` folder with subfolders for each family.
- Each family would have a `family.yaml` file to store common attributes.

This would look like:
```
/monsters
   ├── hobgoblins
   │   ├── family.yaml
   │   ├── hobgoblin-soldier.yaml
   │   └── ...
   ├── beasts
   │   ├── family.yaml
   │   └── owlbear.yaml
   ├── plants
   │   ├── family.yaml
   │   └── spore-octopus.yaml
   └── elementals-fire
       ├── family.yaml
       ├── emberling.yaml
       └── ...
```

A family.yaml file would look something like this:
```yaml
# hobgoblins/family.yaml
name: Hobgoblins
slug: hobgoblins
ability:
  name: Hammer the Gap
  description: Once per round as a reaction, make a melee attack against a hero damaged by another creature for free.
```

Monster files would be really nice and short as well:
```yaml
# hobgoblins/hobgoblin-soldier.yaml
name: Hobgoblin Soldier
slug: hobgoblin-soldier
level: "1"
armor: H
hp: 15
actions:
  - name: Longsword
    damage: "1d8+1"
  - name: Longbow
    damage: "1d8+1"
    range: "10-120"
```

This setup makes it easy to add new families or monsters without editing a large YAML file—just drop in a new folder or file as needed! You’d only need a simple function to loop through the folders and read in all the families and monsters. I’d be happy to work on a script for that if time allows.

This approach also sets you up for future scalability if the monster list grows large, as it would make lazy loading easier down the road. But that’s probably a ways off 😊

Let me know what you think!
